# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [8]:
#1.1
import numpy as np
array = np.random.randint(1,20,size=(5,5))
array[:,2] = 1
array

array([[ 6,  3,  1,  7,  7],
       [10,  4,  1, 19, 12],
       [ 9, 14,  1, 18,  6],
       [ 7,  9,  1,  5,  4],
       [ 6,  2,  1, 14,  7]])

In [13]:
#1.2
array = np.arange(1,17).reshape(4,4)
array

np.fill_diagonal(array,0)
array

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [ ]:
#2.1
array = np.arange(1,37).reshape(6,6)
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [16]:
sub_arr = array[2:5,1:4]
sub_arr

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [62]:
#2.2
array = np.random.randint(1,20,size=(5,5))
array

order_elements = np.concat((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
order_elements

array([ 1,  9,  1,  7, 16,  2,  4, 15, 11, 14, 17,  9,  4,  4, 13, 10])

In [ ]:
#3.1
array1 = np.random.randint(1,11,size=(3,4))
array2 = np.random.randint(1,11,size=(3,4))
print(array1)
print(array2)

[[ 7  1  8  3]
 [ 1  9  5  6]
 [10  2  6  2]]
[[ 8  7 10  1]
 [ 3 10 10  1]
 [ 8  8  9  6]]


In [76]:
sum_arr = array1 + array2
sub_arr = array1 - array2
mul_arr = array1 * array2
div_arr = array1 / array2
print(sum_arr)
print(sub_arr)
print(mul_arr)
print(div_arr)

[[10 18 18 12]
 [ 7 18 10  9]
 [18 18  9 13]]
[[-6 -2  0 -4]
 [-3  0  4  7]
 [-2  0 -7 -3]]
[[16 80 81 32]
 [10 81 21  8]
 [80 81  8 40]]
[[0.25       0.8        1.         0.5       ]
 [0.4        1.         2.33333333 8.        ]
 [0.8        1.         0.125      0.625     ]]


In [78]:
#3.2
array = np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#print(array.sum(axis=0))
row_sum = np.sum(array,axis=1)
print(row_sum)

[10 26 42 58]


In [84]:
#print(array.sum(axis=1))
col_sum = np.sum(array,axis=0)
print(col_sum)

[28 32 36 40]


In [86]:
#4.1
array = np.random.randint(1,21,size=(5,5))
print("Array: \n",array)

Array: 
 [[12  4 15  4  8]
 [ 4 12  9  1  2]
 [ 3 11  2  3  4]
 [16 18 19  1 19]
 [ 9 20 17  7  1]]


In [91]:
arr_mean = np.mean(array)
print(arr_mean)
arr_median = np.median(array)
print(arr_median)
arr_std = np.std(array)
print(arr_std)
arr_var = np.var(array)
print(arr_var)

8.84
8.0
6.447821337475164
41.574400000000004


In [93]:
#4.2
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr_mean = np.mean(array)
print(arr_mean)
arr_std = np.std(array)
print(arr_std)

normalization = (array - arr_mean)/arr_std
print(normalization)


5.0
2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [99]:
#5.1
array = np.random.randint(1,11,size=(3,3))
print("Original Array: \n",array)

Original Array: 
 [[3 2 6]
 [4 9 1]
 [4 7 4]]


In [101]:
row_array = np.random.randint(1,11,size=(3,))
print(row_array)

[4 6 2]


In [103]:
result = array + row_array
print(result)

[[ 7  8  8]
 [ 8 15  3]
 [ 8 13  6]]


In [105]:
#5.2
array = np.random.randint(1,10,size=(4,4))
print("Original Array:\n",array)

Original Array:
 [[7 2 4 9]
 [6 6 1 9]
 [7 1 7 3]
 [4 5 3 9]]


In [106]:
col_sub = np.random.randint(1,11,size=(4,))
print("Column :\n",col_sub)

Column :
 [4 9 6 1]


In [107]:
result = array - col_sub
print("result: \n",result)

result: 
 [[ 3 -7 -2  8]
 [ 2 -3 -5  8]
 [ 3 -8  1  2]
 [ 0 -4 -3  8]]


#### Determinant
What it is: A single number that summarizes certain properties of a square matrix.
Meaning:
If determinant = 0 → the matrix is singular (no inverse exists).
If determinant ≠ 0 → the matrix is invertible.
Formula example (2×2 matrix):
matrix = ad - bc

#### Inverse
What it is: Another matrix that, when multiplied with the original, gives the identity matrix.
Exists only if: The determinant is non-zero.
Property:
A*A^{-1} = I

####  Eigenvalues (and Eigenvectors)
What they are:
Eigenvalues tell you how much a transformation stretches or compresses along certain directions.
Eigenvectors are those special directions that don’t change orientation when the transformation is applied.
Equation:
A.v = lambda.v
Where:
v is the eigenvector
lambda is the eigenvalue

In [109]:
#6.1
matrix = np.random.randint(1,11,size=(3,3))
print("Original Matrix: \n", matrix)

Original Matrix: 
 [[5 3 7]
 [3 2 8]
 [2 7 9]]


In [110]:
#determinant
determinant = np.linalg.det(matrix)
print("Determinant: \n", determinant)


Determinant: 
 -103.99999999999999


In [111]:
#Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse: \n", inverse)


Inverse: 
 [[ 0.36538462 -0.21153846 -0.09615385]
 [ 0.10576923 -0.29807692  0.18269231]
 [-0.16346154  0.27884615 -0.00961538]]


In [112]:
#Compute the eigenValues
eigenvalues = np.linalg.eigvals(matrix)
print("EigenValues: \n", eigenvalues)


EigenValues: 
 [15.96786798  2.56819023 -2.53605821]


In [ ]:
#6.2
arr1 = np.random.randint(1,11,size=(2,3))
arr2 = np.random.randint(1,11,size=(3,2))
print(arr1)
print(arr2)

[[3 3 5]
 [8 4 5]]
[[ 1  5]
 [ 1  2]
 [10  4]]


In [115]:
result = np.dot(arr1,arr2)
print("Result: \n",result)


Result: 
 [[56 41]
 [62 68]]


In [117]:
#7.1
array = np.arange(1,10).reshape(3,3)
print("Original Array: \n",array)

Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [119]:
print(array.reshape(1,9))
print(array.reshape(9,1))

[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
#7.2
array = np.random.randint(1,21,size=(5,5))
print("ORiginal Array: \n",array)

ORiginal Array: 
 [[ 8  3 16 15 10]
 [ 4  7  3 20 17]
 [14  5 15  2 14]
 [ 8 16  3  4 11]
 [ 9  3 16 20 13]]


In [121]:
array_flatten = array.flatten()
print("FLatten Array: \n",array_flatten)

FLatten Array: 
 [ 8  3 16 15 10  4  7  3 20 17 14  5 15  2 14  8 16  3  4 11  9  3 16 20
 13]


In [122]:
print(array_flatten.reshape(5,5))

[[ 8  3 16 15 10]
 [ 4  7  3 20 17]
 [14  5 15  2 14]
 [ 8 16  3  4 11]
 [ 9  3 16 20 13]]


In [136]:
#8.1
array = np.random.randint(1,21,size=(5,5))
print("ORiginal Array: \n",array)

ORiginal Array: 
 [[ 1 11  5 15 20]
 [16 19  8  6 20]
 [10 12  6  9 18]
 [13  4 11  3  2]
 [17  5 20 17  4]]


In [144]:
array_corner = array[[0,0,-1,-1],[0,-1,0,-1]]
print(array_corner)

[ 1 20 17  4]


In [145]:
#8.2
array = np.random.randint(1,21,size=(4,4))
print("ORiginal Array: \n",array)

ORiginal Array: 
 [[ 5 16  9  8]
 [20  4 19 13]
 [ 7  4  2  2]
 [16 20  5 14]]


In [146]:
array[array > 10] = 10
array

array([[ 5, 10,  9,  8],
       [10,  4, 10, 10],
       [ 7,  4,  2,  2],
       [10, 10,  5, 10]])

In [149]:
#9.1

#define datatype
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alan',25,200),('Jenifer',23,120),('Makuto',18,90)],dtype=data_type)
data

array([('Alan', 25, 200.), ('Jenifer', 23, 120.), ('Makuto', 18,  90.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [151]:
sorted_array = np.sort(data,order='age')
sorted_array

array([('Makuto', 18,  90.), ('Jenifer', 23, 120.), ('Alan', 25, 200.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [152]:
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype = data_type)
data

array([(1, 2), (3, 4), (5, 6)], dtype=[('x', '<i4'), ('y', '<i4')])

In [153]:
#Euclidean distance is the straight-line distance between two points in space — the same way you’d measure with a ruler.
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
distances

array([[0.        , 2.82842712, 5.65685425],
       [2.82842712, 0.        , 2.82842712],
       [5.65685425, 2.82842712, 0.        ]])

In [159]:
#10.1
import numpy.ma as ma
array = np.random.randint(1,21,size=(4,4))
masked_array = ma.masked_greater(array,10)
print("original Array: \n",array)
print("Maksed Array: \n",masked_array)

original Array: 
 [[ 8  3 12  1]
 [ 6 20  8 18]
 [ 5 15 18 17]
 [20 10  9  8]]
Maksed Array: 
 [[8 3 -- 1]
 [6 -- 8 --]
 [5 -- -- --]
 [-- 10 9 8]]


In [166]:
#10.2
array = np.random.randint(1,21,size=(3,3))
print("Original array: \n",array)

Original array: 
 [[20 18 13]
 [ 5  7 13]
 [ 6  1  1]]


In [167]:
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
masked_array

masked_array(
  data=[[--, 18, 13],
        [5, --, 13],
        [6, 1, --]],
  mask=[[ True, False, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=999999)

In [168]:
mean_unmasked= masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print(masked_array)

[[ 9 18 13]
 [ 5  9 13]
 [ 6  1  9]]
