#### Numpy - is Funadamental in scientifical computing in python. It provides support for arrays and matrices along with a collection of mathematical functions to operate on the data structures. 

In [ ]:
import numpy as np

##Create arrays using numpy
##1-D Array
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
##2-D Array
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))

array([[1, 2, 3, 4, 5]])

In [9]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [13]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
print(type(np.array((1,2,3))))
print(type(np.array([1,2,3])))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [20]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
##Attributes of Numpy Array

arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n", arr)
print("Array Shape: ", arr.shape)
print("Number of dimension in Array: ",arr.ndim)
print("Size (number of elements in Array): ", arr.size)
print("Arrays Datatype: ", arr.dtype)
print("Array ItemSize (in Bytes): ",arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Array Shape:  (2, 3)
Number of dimension in Array:  2
Size (number of elements in Array):  6
Arrays Datatype:  int64
Array ItemSize (in Bytes):  8


In [23]:
##Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ", arr1 + arr2)
print("Substraction: ", arr1 - arr2)
print("Multiplication: ", arr1 * arr2)
print("Division: ", arr1 / arr2 )

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [25]:
#Universal Function
arr = np.array([1,2,3,4,5])

##square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [26]:
##array slicing and indexing 
arr = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
print("Array: \n", arr)

Array: 
 [[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [42]:
#print(arr[0][0])
#print(arr[0:2,3:])
print(arr[1:,1:3])

[[3 4]
 [4 5]]


In [32]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [44]:
#Modifying array elements
arr[0][0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  2,   3,   4,   5,   6],
       [  3,   4,   5,   6,   7]])

In [45]:
arr[1:] = 100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [46]:
## statistical Concepts - Normalization
##To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

#calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalization
normalization = (data - mean) /std_dev
print("Normalized Data: ", normalization)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
#Mean 
mean = np.mean(arr)
print("Mean: ",mean)

#Median 
median = np.median(arr)
print("Median: ",median)

#standard deviation 
standard_deviation = np.std(arr)
print("Standard Deviation: ",standard_deviation)

#Variance 
variance = np.var(data)
print("Variance: ",variance)



Mean:  74.26666666666667
Median:  100.0
Standard Deviation:  42.67781104456454
Variance:  2.0


In [50]:
##Logical operations
data = np.array([1,2,3,4,5,6,7,8,9])
print(data[data>5])

[6 7 8 9]


In [51]:
## need to used & instead of "and"
print(data[(data >= 5) & (data <= 8)])

[5 6 7 8]
